const F=["マリオ", "ドンキーコング", "リンク", "サムス", "ダークサムス", "ヨッシー", "カービィ", "フォックス", "ピカチュウ", "ルイージ", "ネス", "キャプテン・ファルコン", "プリン", "ピーチ", "デイジー", "クッパ", "アイスクライマー", "シーク", "ゼルダ", "ドクターマリオ", "ピチュー", "ファルコ", "マルス", "ルキナ", "こどもリンク", "ガノンドロフ", "ミュウツー", "ロイ", "クロム", "Mr.ゲーム＆ウォッチ", "メタナイト", "ピット", "ブラックピット", "ゼロスーツサムス", "ワリオ", "スネーク", "アイク", "ポケモントレーナー", "ディディーコング", "リュカ", "ソニック", "デデデ", "ピクミン＆オリマー", "ルカリオ", "ロボット", "トゥーンリンク", "ウルフ", "むらびと", "ロックマン", "Wii Fit トレーナー", "ロゼッタ＆チコ", "リトル・マック", "ゲッコウガ", "Mii 格闘タイプ", "Mii 剣術タイプ", "Mii 射撃タイプ", "パルテナ", "パックマン", "ルフレ", "シュルク", "クッパJr.", "ダックハント", "リュウ", "ケン", "クラウド", "カムイ", "ベヨネッタ", "インクリング", "リドリー", "シモン", "リヒター", "キングクルール", "しずえ", "ガオガエン", "パックンフラワー", "ジョーカー", "勇者", "バンジョー＆カズーイ", "テリー", "ベレト／ベレス", "ミェンミェン", "スティーブ／アレックス", "セフィロス", "ホムラ／ヒカリ", "カズヤ", "ソラ"];
const ICON={"マリオ": "MarioHeadSSBU.png", "ドンキーコング": "DonkeyKongHeadSSBU.png", "リンク": "LinkHeadSSBU.png", "サムス": "SamusHeadSSBU.png", "ダークサムス": "DarkSamusHeadSSBU.png", "ヨッシー": "YoshiHeadSSBU.png", "カービィ": "KirbyHeadSSBU.png", "フォックス": "FoxHeadSSBU.png", "ピカチュウ": "PikachuHeadSSBU.png", "ルイージ": "LuigiHeadSSBU.png", "ネス": "NessHeadSSBU.png", "キャプテン・ファルコン": "CaptainFalconHeadSSBU.png", "プリン": "JigglypuffHeadSSBU.png", "ピーチ": "PeachHeadSSBU.png", "デイジー": "DaisyHeadSSBU.png", "クッパ": "BowserHeadSSBU.png", "アイスクライマー": "IceClimbersHeadSSBU.png", "シーク": "SheikHeadSSBU.png", "ゼルダ": "ZeldaHeadSSBU.png", "ドクターマリオ": "DrMarioHeadSSBU.png", "ピチュー": "PichuHeadSSBU.png", "ファルコ": "FalcoHeadSSBU.png", "マルス": "MarthHeadSSBU.png", "ルキナ": "LucinaHeadSSBU.png", "こどもリンク": "YoungLinkHeadSSBU.png", "ガノンドロフ": "GanondorfHeadSSBU.png", "ミュウツー": "MewtwoHeadSSBU.png", "ロイ": "RoyHeadSSBU.png", "クロム": "ChromHeadSSBU.png", "Mr.ゲーム＆ウォッチ": "MrGame&WatchHeadSSBU.png", "メタナイト": "MetaKnightHeadSSBU.png", "ピット": "PitHeadSSBU.png", "ブラックピット": "DarkPitHeadSSBU.png", "ゼロスーツサムス": "ZeroSuitSamusHeadSSBU.png", "ワリオ": "WarioHeadSSBU.png", "スネーク": "SnakeHeadSSBU.png", "アイク": "IkeHeadSSBU.png", "ポケモントレーナー": "PokémonTrainerHeadSSBU.png", "ディディーコング": "DiddyKongHeadSSBU.png", "リュカ": "LucasHeadSSBU.png", "ソニック": "SonicHeadSSBU.png", "デデデ": "KingDededeHeadSSBU.png", "ピクミン＆オリマー": "OlimarHeadSSBU.png", "ルカリオ": "LucarioHeadSSBU.png", "ロボット": "ROBHeadSSBU.png", "トゥーンリンク": "ToonLinkHeadSSBU.png", "ウルフ": "WolfHeadSSBU.png", "むらびと": "VillagerHeadSSBU.png", "ロックマン": "MegaManHeadSSBU.png", "Wii Fit トレーナー": "WiiFitTrainerHeadSSBU.png", "ロゼッタ＆チコ": "Rosalina&LumaHeadSSBU.png", "リトル・マック": "LittleMacHeadSSBU.png", "ゲッコウガ": "GreninjaHeadSSBU.png", "Mii 格闘タイプ": "MiiBrawlerHeadSSBU.png", "Mii 剣術タイプ": "MiiSwordfighterHeadSSBU.png", "Mii 射撃タイプ": "MiiGunnerHeadSSBU.png", "パルテナ": "PalutenaHeadSSBU.png", "パックマン": "Pac-ManHeadSSBU.png", "ルフレ": "RobinHeadSSBU.png", "シュルク": "ShulkHeadSSBU.png", "クッパJr.": "BowserJrHeadSSBU.png", "ダックハント": "DuckHuntHeadSSBU.png", "リュウ": "RyuHeadSSBU.png", "ケン": "KenHeadSSBU.png", "クラウド": "CloudHeadSSBU.png", "カムイ": "CorrinHeadSSBU.png", "ベヨネッタ": "BayonettaHeadSSBU.png", "インクリング": "InklingHeadSSBU.png", "リドリー": "RidleyHeadSSBU.png", "シモン": "SimonHeadSSBU.png", "リヒター": "RichterHeadSSBU.png", "キングクルール": "KingKRoolHeadSSBU.png", "しずえ": "IsabelleHeadSSBU.png", "ガオガエン": "IncineroarHeadSSBU.png", "パックンフラワー": "PiranhaPlantHeadSSBU.png", "ジョーカー": "JokerHeadSSBU.png", "勇者": "HeroHeadSSBU.png", "バンジョー＆カズーイ": "Banjo&KazooieHeadSSBU.png", "テリー": "TerryHeadSSBU.png", "ベレト／ベレス": "BylethHeadSSBU.png", "ミェンミェン": "MinMinHeadSSBU.png", "スティーブ／アレックス": "SteveHeadSSBU.png", "セフィロス": "SephirothHeadSSBU.png", "カズヤ": "KazuyaHeadSSBU.png", "ソラ": "SoraHeadSSBU.png"};
const ICON_BASE="https://www.ssbwiki.com/Special:Redirect/file/";
const STORAGE="smash-prep-data-v1", LEGACY="fresh-counter-data-v1";
let db={tournamentNames:["Beeスマ fresh","ウメブラ"],events:[],players:[]};
const $=s=>document.querySelector(s), dlg=$("#dlg");
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function load(){try{let raw=localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY);if(raw){const x=JSON.parse(raw);if(x&&Array.isArray(x.events))db=x;if(!localStorage.getItem(STORAGE))sync()}}catch(e){console.error(e)}}
function sync(){localStorage.setItem(STORAGE,JSON.stringify(db))}
function today(){const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function fmt(s){const d=new Date(s+"T00:00:00");return `${d.getMonth()+1}/${d.getDate()}`}
function urls(f){if(f==="ホムラ／ヒカリ")return [ICON_BASE+"PyraHeadSSBU.png",ICON_BASE+"MythraHeadSSBU.png"];return ICON[f]?[ICON_BASE+ICON[f]]:[]}
function icon(f,small=false){return urls(f).map(u=>`<img src="${u}" alt="" ${small?"":'loading="lazy"'} onerror="this.style.display='none'">`).join("")}
function render(){const q=$("#search").value.trim().toLowerCase(),sort=$("#sort").value;let es=[...db.events].filter(e=>{const ps=db.players.filter(p=>p.eventId===e.id);return [e.name,...ps.flatMap(p=>[p.name,p.memo,...p.fighters])].join(" ").toLowerCase().includes(q)});es.sort((a,b)=>sort==="name"?a.name.localeCompare(b.name,"ja"):(sort==="asc"?1:-1)*a.date.localeCompare(b.date));$("#events").innerHTML=es.map(e=>{const ps=db.players.filter(p=>p.eventId===e.id);return `<article class="event"><div class="eventHead" onclick="toggle('${e.id}')"><div><div class="date">${fmt(e.date)}</div><div class="eventName">${esc(e.name)}</div><div class="muted">${ps.length}人登録</div></div><button class="ghost" onclick="event.stopPropagation();editEvent('${e.id}')">編集</button></div><div class="players" id="p-${e.id}" hidden>${ps.map(p=>`<div class="player" onclick="editPlayer('${p.id}')"><div><b>${esc(p.name)}</b><div class="chips">${p.fighters.map(f=>`<span class="chip">${esc(f)}</span>`).join("")}</div>${p.memo?`<div class="memo">${esc(p.memo)}</div>`:""}</div><span>›</span></div>`).join("")}<button class="addPlayer" onclick="addPlayer('${e.id}')">＋ プレイヤーを追加</button></div></article>`}).join("")||`<section class="emptyState"><b>大会がまだ登録されていません</b><span>最初の大会を追加してください。</span><button onclick="eventForm()">＋ 大会を追加</button></section>`}
window.toggle=id=>{const x=$("#p-"+id);x.hidden=!x.hidden};
function eventForm(id){const e=db.events.find(x=>x.id===id),names=db.tournamentNames;dlg.innerHTML=`<h2>${e?"大会を編集":"大会を追加"}</h2><label>開催日</label><input id="edate" type="date" value="${e?.date||today()}"><label>大会名</label><select id="ename"><option value="">大会名を選択</option>${names.map(n=>`<option ${e?.name===n?"selected":""}>${esc(n)}</option>`).join("")}</select><label>新しい大会名を登録</label><div class="row"><input id="newname" placeholder="例：Beeスマ fresh"><button id="regname">登録して選択</button></div><div class="row actionRow"><button id="saveE">${e?"変更を保存":"大会を追加"}</button>${e?'<button id="delE" class="danger">削除</button>':""}<button class="ghost" onclick="dlg.close()">閉じる</button></div>`;dlg.showModal();
$("#regname").onclick=()=>{const n=$("#newname").value.trim();if(!n)return alert("大会名を入力してください");if(db.tournamentNames.some(x=>x.toLowerCase()===n.toLowerCase()))return alert("同じ大会名がすでに登録されています。");db.tournamentNames.push(n);sync();const d=$("#edate").value;eventForm(id);$("#edate").value=d;$("#ename").value=n};
$("#saveE").onclick=()=>{const date=$("#edate").value,name=$("#ename").value;if(!date||!name)return alert("開催日と大会名を選択してください");if(e)Object.assign(e,{date,name});else db.events.push({id:crypto.randomUUID(),date,name});sync();dlg.close();render()};
if(e)$("#delE").onclick=()=>{if(confirm("この大会と登録プレイヤーを削除しますか？")){db.players=db.players.filter(p=>p.eventId!==id);db.events=db.events.filter(x=>x.id!==id);sync();dlg.close();render()}}}
window.editEvent=id=>eventForm(id);window.addPlayer=id=>playerForm(null,id);window.editPlayer=id=>{const p=db.players.find(x=>x.id===id);playerForm(p,p.eventId)};
function playerForm(p,eventId){const selected=new Set(p?.fighters||[]);dlg.innerHTML=`<h2>${p?"プレイヤー編集":"プレイヤー追加"}</h2><label>名前</label><input id="pname" value="${esc(p?.name||"")}"><label>使用キャラ（複数選択可）</label><div class="selectedFighters" id="selectedFighters"></div><button class="chooseFighter" id="chooseFighter">＋ キャラを選択</button><div class="fighterPicker" id="fighterPicker" hidden><div class="fighterPickerHead"><b>キャラクターを選択</b><button class="ghost" id="closePicker">完了</button></div><div class="fighterGrid">${F.map(f=>`<button class="fighter ${selected.has(f)?"on":""}" data-f="${esc(f)}"><span class="fighterIconWrap">${icon(f)}<span class="fighterFallback">${esc(f).slice(0,2)}</span></span><span class="fighterName">${esc(f)}</span></button>`).join("")}</div></div><label>対策メモ</label><textarea id="pmemo">${esc(p?.memo||"")}</textarea><div class="row actionRow"><button id="saveP">保存</button>${p?'<button id="delP" class="danger">削除</button>':""}<button class="ghost" onclick="dlg.close()">閉じる</button></div>`;dlg.showModal();
const draw=()=>$("#selectedFighters").innerHTML=[...selected].map(f=>`<span class="selectedChip">${icon(f,true)}${esc(f)}</span>`).join("");draw();
$("#chooseFighter").onclick=()=>$("#fighterPicker").hidden=false;$("#closePicker").onclick=()=>$("#fighterPicker").hidden=true;
dlg.querySelectorAll(".fighter").forEach(b=>b.onclick=()=>{const f=b.dataset.f;selected.has(f)?selected.delete(f):selected.add(f);b.classList.toggle("on",selected.has(f));draw()});
$("#saveP").onclick=()=>{const name=$("#pname").value.trim();if(!name)return alert("プレイヤー名を入力してください");const data={eventId,name,fighters:[...selected],memo:$("#pmemo").value};if(p)Object.assign(p,data);else db.players.push({id:crypto.randomUUID(),...data});sync();dlg.close();render()};
if(p)$("#delP").onclick=()=>{if(confirm("このプレイヤーを削除しますか？")){db.players=db.players.filter(x=>x.id!==p.id);sync();dlg.close();render()}}}
$("#addEvent").onclick=()=>eventForm();$("#search").oninput=render;$("#sort").onchange=render;
$("#exportData").onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`smash-prep-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$("#importData").onclick=()=>$("#importFile").click();$("#importFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!x||!Array.isArray(x.events)||!Array.isArray(x.players))throw 0;if(confirm("現在のデータを読み込んだバックアップで置き換えますか？")){db=x;sync();render()}}catch{alert("Smash PrepのバックアップJSONを読み込めませんでした。")}e.target.value=""};
load();render();
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.error));
