const F=["マリオ", "ドンキーコング", "リンク", "サムス", "ダークサムス", "ヨッシー", "カービィ", "フォックス", "ピカチュウ", "ルイージ", "ネス", "キャプテン・ファルコン", "プリン", "ピーチ", "デイジー", "クッパ", "アイスクライマー", "シーク", "ゼルダ", "ドクターマリオ", "ピチュー", "ファルコ", "マルス", "ルキナ", "こどもリンク", "ガノンドロフ", "ミュウツー", "ロイ", "クロム", "Mr.ゲーム＆ウォッチ", "メタナイト", "ピット", "ブラックピット", "ゼロスーツサムス", "ワリオ", "スネーク", "アイク", "ポケモントレーナー", "ディディーコング", "リュカ", "ソニック", "デデデ", "ピクミン＆オリマー", "ルカリオ", "ロボット", "トゥーンリンク", "ウルフ", "むらびと", "ロックマン", "Wii Fit トレーナー", "ロゼッタ＆チコ", "リトル・マック", "ゲッコウガ", "Mii 格闘タイプ", "Mii 剣術タイプ", "Mii 射撃タイプ", "パルテナ", "パックマン", "ルフレ", "シュルク", "クッパJr.", "ダックハント", "リュウ", "ケン", "クラウド", "カムイ", "ベヨネッタ", "インクリング", "リドリー", "シモン", "リヒター", "キングクルール", "しずえ", "ガオガエン", "パックンフラワー", "ジョーカー", "勇者", "バンジョー＆カズーイ", "テリー", "ベレト／ベレス", "ミェンミェン", "スティーブ／アレックス", "セフィロス", "ホムラ／ヒカリ", "カズヤ", "ソラ"];
const ICON={"マリオ": "MarioHeadSSBU.png", "ドンキーコング": "DonkeyKongHeadSSBU.png", "リンク": "LinkHeadSSBU.png", "サムス": "SamusHeadSSBU.png", "ダークサムス": "DarkSamusHeadSSBU.png", "ヨッシー": "YoshiHeadSSBU.png", "カービィ": "KirbyHeadSSBU.png", "フォックス": "FoxHeadSSBU.png", "ピカチュウ": "PikachuHeadSSBU.png", "ルイージ": "LuigiHeadSSBU.png", "ネス": "NessHeadSSBU.png", "キャプテン・ファルコン": "CaptainFalconHeadSSBU.png", "プリン": "JigglypuffHeadSSBU.png", "ピーチ": "PeachHeadSSBU.png", "デイジー": "DaisyHeadSSBU.png", "クッパ": "BowserHeadSSBU.png", "アイスクライマー": "IceClimbersHeadSSBU.png", "シーク": "SheikHeadSSBU.png", "ゼルダ": "ZeldaHeadSSBU.png", "ドクターマリオ": "DrMarioHeadSSBU.png", "ピチュー": "PichuHeadSSBU.png", "ファルコ": "FalcoHeadSSBU.png", "マルス": "MarthHeadSSBU.png", "ルキナ": "LucinaHeadSSBU.png", "こどもリンク": "YoungLinkHeadSSBU.png", "ガノンドロフ": "GanondorfHeadSSBU.png", "ミュウツー": "MewtwoHeadSSBU.png", "ロイ": "RoyHeadSSBU.png", "クロム": "ChromHeadSSBU.png", "Mr.ゲーム＆ウォッチ": "MrGame&WatchHeadSSBU.png", "メタナイト": "MetaKnightHeadSSBU.png", "ピット": "PitHeadSSBU.png", "ブラックピット": "DarkPitHeadSSBU.png", "ゼロスーツサムス": "ZeroSuitSamusHeadSSBU.png", "ワリオ": "WarioHeadSSBU.png", "スネーク": "SnakeHeadSSBU.png", "アイク": "IkeHeadSSBU.png", "ポケモントレーナー": "PokémonTrainerHeadSSBU.png", "ディディーコング": "DiddyKongHeadSSBU.png", "リュカ": "LucasHeadSSBU.png", "ソニック": "SonicHeadSSBU.png", "デデデ": "KingDededeHeadSSBU.png", "ピクミン＆オリマー": "OlimarHeadSSBU.png", "ルカリオ": "LucarioHeadSSBU.png", "ロボット": "ROBHeadSSBU.png", "トゥーンリンク": "ToonLinkHeadSSBU.png", "ウルフ": "WolfHeadSSBU.png", "むらびと": "VillagerHeadSSBU.png", "ロックマン": "MegaManHeadSSBU.png", "Wii Fit トレーナー": "WiiFitTrainerHeadSSBU.png", "ロゼッタ＆チコ": "Rosalina&LumaHeadSSBU.png", "リトル・マック": "LittleMacHeadSSBU.png", "ゲッコウガ": "GreninjaHeadSSBU.png", "Mii 格闘タイプ": "MiiBrawlerHeadSSBU.png", "Mii 剣術タイプ": "MiiSwordfighterHeadSSBU.png", "Mii 射撃タイプ": "MiiGunnerHeadSSBU.png", "パルテナ": "PalutenaHeadSSBU.png", "パックマン": "Pac-ManHeadSSBU.png", "ルフレ": "RobinHeadSSBU.png", "シュルク": "ShulkHeadSSBU.png", "クッパJr.": "BowserJrHeadSSBU.png", "ダックハント": "DuckHuntHeadSSBU.png", "リュウ": "RyuHeadSSBU.png", "ケン": "KenHeadSSBU.png", "クラウド": "CloudHeadSSBU.png", "カムイ": "CorrinHeadSSBU.png", "ベヨネッタ": "BayonettaHeadSSBU.png", "インクリング": "InklingHeadSSBU.png", "リドリー": "RidleyHeadSSBU.png", "シモン": "SimonHeadSSBU.png", "リヒター": "RichterHeadSSBU.png", "キングクルール": "KingKRoolHeadSSBU.png", "しずえ": "IsabelleHeadSSBU.png", "ガオガエン": "IncineroarHeadSSBU.png", "パックンフラワー": "PiranhaPlantHeadSSBU.png", "ジョーカー": "JokerHeadSSBU.png", "勇者": "HeroHeadSSBU.png", "バンジョー＆カズーイ": "Banjo&KazooieHeadSSBU.png", "テリー": "TerryHeadSSBU.png", "ベレト／ベレス": "BylethHeadSSBU.png", "ミェンミェン": "MinMinHeadSSBU.png", "スティーブ／アレックス": "SteveHeadSSBU.png", "セフィロス": "SephirothHeadSSBU.png", "カズヤ": "KazuyaHeadSSBU.png", "ソラ": "SoraHeadSSBU.png"};
const ICON_BASE="https://www.ssbwiki.com/Special:Redirect/file/";
const STORAGE="smash-prep-data-v1",LEGACY="fresh-counter-data-v1";
let db={tournamentNames:["Beeスマ fresh","ウメブラ"],events:[],players:[]};
const $=s=>document.querySelector(s),dlg=$("#dlg");
const esc=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function load(){try{let raw=localStorage.getItem(STORAGE)||localStorage.getItem(LEGACY);if(raw){const x=JSON.parse(raw);if(x&&Array.isArray(x.events))db=x;if(!localStorage.getItem(STORAGE))sync()}}catch(e){console.error(e)}}
function sync(){localStorage.setItem(STORAGE,JSON.stringify(db))}
function today(){const d=new Date(),p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function fmt(s){const d=new Date(s+"T00:00:00");return `${d.getMonth()+1}/${d.getDate()}`}
function urls(f){if(f==="ホムラ／ヒカリ")return [ICON_BASE+"PyraHeadSSBU.png",ICON_BASE+"MythraHeadSSBU.png"];return ICON[f]?[ICON_BASE+ICON[f]]:[]}
function fighterIcon(f,small=false){return urls(f).map(u=>`<img src="${u}" alt="" ${small?"":'loading="lazy"'} onerror="this.style.display='none'">`).join("")}
function eventById(id){return db.events.find(e=>e.id===id)}
function eventUrl(id){return `./tournament.html?id=${encodeURIComponent(id)}`}
